In [1]:
import numpy as np

In [3]:
#배열 생성
list1 = [1,2,3]
arr1 = np.array(list1)
arr1

array([1, 2, 3])

In [4]:
#0으로 초기화하여 배열 생성
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
#2 * 3 배열 생성
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
#1로 초기화하여 배열 생성
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [11]:
#np.zeros와 동일한 효과
np.empty(5)

array([0., 0., 0., 0., 0.])

In [13]:
#수의 증감 이용하여 배열 생성
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(20, 30, 2)

array([20, 22, 24, 26, 28])

In [17]:
#랜덤한 숫자로 배열 생성
np.random.rand(2, 3)

array([[0.6445096 , 0.8863217 , 0.27624971],
       [0.59121759, 0.46615087, 0.76284043]])

In [19]:
#데이터를 원하는 차원의 배열로 변경
arr2 = np.arange(16)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [20]:
arr2.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [21]:
arr2.reshape(2, 2, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [23]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
arr.shape

(16,)

In [25]:
arr.dtype

dtype('int32')

In [26]:
arr.astype(float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [28]:
arr[5]

5

In [29]:
arr[-1]

15

In [30]:
arr[5:8]

array([5, 6, 7])

In [33]:
arr2 = np.arange(16).reshape(4, 4)
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [34]:
arr2[1]

array([4, 5, 6, 7])

In [35]:
arr2[1][1]

5

In [36]:
arr2[1, 2]

6

In [37]:
scores = [80, 90, 70, 65, 85, 95, 90, 80, 75, 80]
score_arr = np.array(scores)
score_arr

array([80, 90, 70, 65, 85, 95, 90, 80, 75, 80])

In [38]:
score_arr >= 90

array([False,  True, False, False, False,  True,  True, False, False,
       False])

In [41]:
score_arr[score_arr >= 90] = 999
score_arr

array([ 80, 999,  70,  65,  85, 999, 999,  80,  75,  80])

In [43]:
arr = np.arange(1, 5)
arr

array([1, 2, 3, 4])

In [44]:
arr + 2

array([3, 4, 5, 6])

In [45]:
arr * 2

array([2, 4, 6, 8])

In [46]:
list = [1,2,3,4]
list * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [47]:
arr1 = np.arange(5, 9)
arr1

array([5, 6, 7, 8])

In [48]:
arr + arr1

array([ 6,  8, 10, 12])

In [49]:
list1 = [5, 6, 7, 8]
list + list1

[1, 2, 3, 4, 5, 6, 7, 8]

In [50]:
np.square(arr)

array([ 1,  4,  9, 16], dtype=int32)

In [51]:
np.square(arr)

array([ 1,  4,  9, 16], dtype=int32)

In [52]:
np.exp(arr)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [53]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [55]:
arr = np.arange(10).reshape(2, 5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
arr.transpose()

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [57]:
np.cumsum(arr)

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)